"""Added category column on Product Model

Revision ID: f47cd9d0df18
Revises: 3debe5ec87ef
Create Date: 2024-09-02 14:52:28.009098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47cd9d0df18'
down_revision = '3debe5ec87ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
